name: Mathesis - API
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.16.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Run Build
        run: npm run build
      - name: SSH Remote Commands
        # You may pin to the exact commit or the version.
        # uses: appleboy/ssh-action@55dabf81b49d4120609345970c91507e2d734799
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${{secrets.GOOGLE_CLOUD_VM_SSH}}
          host: ${{secrets.GOOGLE_CLOUD_VM_IP}}
          username: ${{secrets.GOOGLE_CLOUD_VM_USERNAME}}
          script: |
            pm2 delete all
            cd /var/app/mathesis
            git pull
            npm install
            pm2 start nmp-- start
